USE CGDatabase;

DROP TABLE IF EXISTS Job_History;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Countries;
DROP TABLE IF EXISTS Jobs;
DROP TABLE IF EXISTS Regions;